### ISSUE TITLE
How can I unset / invalidate cache?

### ISSUE THREAD

**Issue by gustawdaniel** [pasupulaphani/node-cache-redis#40]
I found `del` method in

https://github.com/pasupulaphani/node-cache-redis/blob/master/src/redisCache.ts#L135

```
/**
 * Delete keys
 * @param keys - keys for the value stored
 * @returns The number of keys that were removed.
 */
export const del = (_keys: string[] = []): Promise<number> =>
  getStore().del(_keys)
```

but I propose to move it to documentation. Additionally after instalation I can see only `dist` and can't see typescript of this package in node modules.

__

Update:

I found link to:

https://pasupulaphani.github.io/node-cache-redis/modules/_rediscache_.html#init

but is should not be described as:

```
init([options]) TSDOC init
```

but rather `Full API` or `All methods` because not only init is described here.

**Comment by pasupulaphani** [comment]
Thank you for your suggestion.

Regarding `del` method doc is available https://pasupulaphani.github.io/node-cache-redis/modules/_rediscache_.html#del

Regarding typescript files not available in the distribution package, I'll have a look today or tomorrow.

**Comment by pasupulaphani** [comment]
Types declarations are available in the published package.
