### ISSUE TITLE
How can I use "import" statement instead of "require" on TypeScript

### ISSUE THREAD

**Issue by john-apisit** [pasupulaphani/node-cache-redis#41]
Hi guys, the library is really usefull. I am implementing it to my new TypeScript project. 
The document recommends to use `const { init, set, get } = require("node-cache-redis")` that cause the TypeScript data type not available. 

Do you have any suggestion? Is there anywhere to install its data type.

**Comment by pasupulaphani** [comment]
Hi @john-apisit , sry, I think the types are not exported in the build. Will fix that today or tomorrow.

**Comment by pasupulaphani** [comment]
The latest npm distribution 6.2.0 should have type declarations.

**Comment by john-apisit** [comment]
Cool! Thanks @pasupulaphani , it is working.
