### ISSUE TITLE
defaulTtlInS wrong parameter name after upgrade from 6.1.0 up to latest

### ISSUE THREAD

**Issue by lexxanatoli** [pasupulaphani/node-cache-redis#46]
Hi

After upgrade from 6.1.0 up to latest, there is a problem with defaultTtlInS parameter in the constructor.
There is an error in TypeScript, because there is a mistake in the param name.

Instead of **defaultTtlInS** there is wrong name **defaulTtlInS** . As you can see there is missed "t" letter.

**Comment by pasupulaphani** [comment]
Thank you for raising the issue. Please note that the typo is now fixed in the version 6.3.1

**Comment by lexxanatoli** [comment]
Thanks, @pasupulaphani
