### ISSUE TITLE
Documentation: getting started?

### ISSUE THREAD

**Issue by victorbadila** [pasupulaphani/node-cache-redis#59]
How do you actually use this? Where do you put the connection string? The documentation does not mention any practical example and the links to node-redis (for RedisOptions obj for example) leads nowhere. A more detailed getting started would surely help.

**Comment by pasupulaphani** [comment]
Apologies, the init doc is here: https://pasupulaphani.github.io/node-cache-redis/index.html#init

Thank you for raising the issue. Updated readme as well.

**Comment by victorbadila** [comment]
Thanks!
